# Generated by Django 2.1.4 on 2018-12-04 14:49

from django.db import migrations
from django.contrib.auth.models import User


def create_users(apps, schema_editors):
    User.objects.create_superuser(username='root', password='root', email='')
    User.objects.create_superuser(username='tech', password='tech', email='')
    User.objects.create_superuser(username='job', password='job', email='')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
